# Generated by Django 3.2 on 2021-04-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210418_1131'),
        ('login', '0005_auto_20210416_1925'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RoomManager',
            new_name='Admin',
        ),
    ]
