# Generated by Django 3.2 on 2021-04-25 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_auto_20210418_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_no',
            new_name='storage_location',
        ),
    ]
